In [1]:
import pandas as pd
import sqlite3

In [ ]:
jobs = pd.read_csv("C:/Users/lenovo/OneDrive/Desktop/Projects/Job Market Intelligence/data/processed/jobs_clean.csv")

In [8]:
conn =sqlite3.connect("../sql/job_market.db")

In [9]:
jobs.to_sql(
    "jobs",
    conn,
    if_exists = "replace",
    index = False
)

61953

1. View the dataset

In [11]:
pd.read_sql(
    "SELECT * FROM jobs LIMIT 5;",
    conn
)

,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,...,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens,experience_level
0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,15 hours ago,Full-time,...,101K–143K,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']",Mid
1,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,12 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],Mid
2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",via Indeed,Overview:\n\nWe are seeking a full-time...\nAe...,"['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...,NaN,18 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql'],Mid
3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,NaN,12 hours ago,Contractor,...,15–25,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']",Mid
4,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,7 hours ago,Contractor,...,90K–110K,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']",Mid

2. Top 20 Hiring Companies

In [18]:
pd.read_sql(
    """
    SELECT company_name, COUNT(*) AS total_jobs
    FROM jobs
    GROUP BY company_name
    ORDER BY total_jobs DESC
    LIMIT 20;
""",
conn
)

                        company_name  total_jobs
0                             Upwork        7533
1                       Talentify.io        2118
2                            Walmart        1829
3                       vmysmartpros        1415
4                               Dice         862
5                       EDWARD JONES         747
6                          Corporate         612
7                 Cox Communications         538
8                     Insight Global         483
9                               iSay         353
10                       MYSMARTPROS         266
11               Centene Corporation         242
12                               ATC         199
13                           Harnham         171
14  Staffigo Technical Services, LLC         167
15                      Apex Systems         163
16                            Leidos         151
17  Saint Louis County Clerks Office         138
18                        Sam's Club         136
19                     CareerBuilder         136

3. Average Salary by Experience Level

In [19]:
pd.read_sql(
    """
    SELECT
    experience_level,
    AVG(salary_standardized) AS average_salary
FROM jobs
GROUP BY experience_level
ORDER BY average_salary DESC;
""",
    conn
)

  experience_level  average_salary
0             Lead   132522.480183
1          Manager   118639.045181
2           Senior   107737.168563
3              Mid    88477.305212
4           Junior    64469.410000
5           Intern    50024.936496

4. Jobs with Salary Greater than $100,000

In [23]:
pd.read_sql(
    """
    SELECT *
    FROM jobs
    WHERE salary_standardized > 100000;
""",
    conn
)

,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,...,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens,experience_level
0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,15 hours ago,Full-time,...,101K–143K,a year,122000.00,101000.0,143000.00,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']",Mid
1,Senior Data Analyst,Aquent,Anywhere,via LinkedIn,The Research Data Analyst is responsible for d...,"['14 hours ago', '54.00–60.52 an hour', 'Work ...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,https://encrypted-tbn0.gstatic.com/images?q=tb...,14 hours ago,NaN,...,54.00–60.52,an hour,57.26,54.0,60.52,57.26,NaN,119100.8,['sql'],Senior
2,Mid-level Claims Data Analyst,CIBA Insurance Services,United States,via KSNT Jobs,"Established in 1993, CIBA Insurance Services o...","['10 hours ago', '90K–130K a year', 'Full-time...",eyJqb2JfdGl0bGUiOiJNaWQtbGV2ZWwgQ2xhaW1zIERhdG...,NaN,10 hours ago,Full-time,...,90K–130K,a year,110000.00,90000.0,130000.00,NaN,110000.0,110000.0,"['excel', 'mssql', 'ssrs', 'sql']",Mid
3,Data Analytics Mentor for Online Bootcamp,Upwork,Anywhere,via Upwork,Company Overview\n\nUpright is the leading wor...,"['12 hours ago', '50–80 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5dGljcyBNZW50b3...,NaN,12 hours ago,Contractor,...,50–80,an hour,65.00,50.0,80.00,65.00,NaN,135200.0,[],Mid
4,Production Support Data Analyst (Open),Sompo International,United States,via LinkedIn,The Production Support Data Analyst is a hands...,"['7 hours ago', '95K–150K a year', 'Full-time'...",eyJqb2JfdGl0bGUiOiJQcm9kdWN0aW9uIFN1cHBvcnQgRG...,https://encrypted-tbn0.gstatic.com/images?q=tb...,7 hours ago,Full-time,...,95K–150K,a year,122500.00,95000.0,150000.00,NaN,122500.0,122500.0,"['c', 'sap', 'sql']",Mid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3587,Marketing Data & BI Analyst II,EDWARD JONES,"Houstonia, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '76,798–130,764 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJNYXJrZXRpbmcgRGF0YSBcdTAwMj...,NaN,23 hours ago,Full-time,...,76798–130764,a year,103781.00,76798.0,130764.00,NaN,103781.0,103781.0,"['power_bi', 'tableau', 'excel', 'snowflake', ...",Mid
3588,Lead-Data Analyst,EDWARD JONES,"Marshfield, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '106,916–182,047 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJMZWFkLURhdGEgQW5hbHlzdCIsIm...,NaN,23 hours ago,Full-time,...,106916–182047,a year,144481.50,106916.0,182047.00,NaN,144481.5,144481.5,[],Lead
3589,Lead-Data Analyst,EDWARD JONES,"High Point, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '106,916–182,047 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJMZWFkLURhdGEgQW5hbHlzdCIsIm...,NaN,23 hours ago,Full-time,...,106916–182047,a year,144481.50,106916.0,182047.00,NaN,144481.5,144481.5,[],Lead
3590,Lead-Data Analyst,EDWARD JONES,"Calhoun, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '106,916–182,047 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJMZWFkLURhdGEgQW5hbHlzdCIsIm...,NaN,23 hours ago,Full-time,...,106916–182047,a year,144481.50,106916.0,182047.00,NaN,144481.5,144481.5,[],Lead
3591,Institutional Credit Management - Lending Data...,Citi,United States,via My ArkLaMiss Jobs,The Institutional Credit Management (ICM) grou...,"['24 hours ago', '105,850–158,780 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJJbnN0aXR1dGlvbmFsIENyZWRpdC...,https://encrypted-tbn0.gstatic.com/images?q=tb...,24 hours ago,Full-time,...,105850–158780,a year,132315.00,105850.0,158780.00,NaN,132315.0,132315.0,"['tableau', 'cognos']",Mid

5. Senior Jobs with Salary Greater than $100,000

In [24]:
pd.read_sql(
    """
    SELECT *
FROM jobs
WHERE experience_level = 'Senior'
AND salary_standardized > 100000;
""",
    conn
)

,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,...,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens,experience_level
0,Senior Data Analyst,Aquent,Anywhere,via LinkedIn,The Research Data Analyst is responsible for d...,"['14 hours ago', '54.00–60.52 an hour', 'Work ...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,https://encrypted-tbn0.gstatic.com/images?q=tb...,14 hours ago,NaN,...,54.00–60.52,an hour,57.26,54.0,60.52,57.26,NaN,119100.8,['sql'],Senior
1,"Senior Data Scientist, Product Analytics",Gusto,United States,via Ai-Jobs.net,"Gusto has physical office spaces in Denver, Sa...","['21 hours ago', '152K–176K a year', 'Full-tim...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBTY2llbnRpc3...,NaN,21 hours ago,Full-time,...,152K–176K,a year,164000.00,152000.0,176000.00,NaN,164000.0,164000.0,"['sql', 'r', 'python']",Senior
2,Senior Data Analyst,eTeam,Anywhere,via LinkedIn,Title: Senior Data Analyst\n\nLocation: 100% R...,"['12 hours ago', '55–60 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,https://encrypted-tbn0.gstatic.com/images?q=tb...,12 hours ago,Contractor,...,55–60,an hour,57.50,55.0,60.00,57.50,NaN,119600.0,"['sas', 'sql']",Senior
3,Sr. Data Systems Analyst,Modis,Anywhere,via LinkedIn,Akkodis is seeking a Sr. Data Systems Analyst ...,"['6 hours ago', '65–95 an hour', 'Work from ho...",eyJqb2JfdGl0bGUiOiJTci4gRGF0YSBTeXN0ZW1zIEFuYW...,https://encrypted-tbn0.gstatic.com/images?q=tb...,6 hours ago,Contractor,...,65–95,an hour,80.00,65.0,95.00,80.00,NaN,166400.0,"['t-sql', 'go', 'ssis', 'sql']",Senior
4,IT Sr Data Analyst,Aurora Organic Dairy,"Boulder, CO",LinkedIn,IT Senior Data Analyst\n\nPurpose\n\nWe are se...,"['1 day ago', '100K–130K a year', 'Full-time']",eyJqb2JfdGl0bGUiOiJJVCBTciBEYXRhIEFuYWx5c3QiLC...,https://serpapi.com/searches/67f4913692bafe9ec...,1 day ago,Full-time,...,100K–130K,a year,115000.00,100000.0,130000.00,NaN,115000.0,115000.0,"['power_bi', 'sap', 'sql', 'azure']",Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
641,Senior Data Analyst,Harnham,United States,via My ArkLaMiss Jobs,SENIOR DATA ANALYST\n\nREMOTE - NEED TO WORK P...,"['15 hours ago', '120K–140K a year', 'Full-time']",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,NaN,15 hours ago,Full-time,...,120K–140K,a year,130000.00,120000.0,140000.00,NaN,130000.0,130000.0,"['power_bi', 'tableau', 'looker', 'sql']",Senior
642,Senior Business Systems Analyst (Remote),EDWARD JONES,"Hartsburg, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['15 hours ago', '76,798–130,764 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgQnVzaW5lc3MgU3lzdG...,NaN,15 hours ago,Full-time,...,76798–130764,a year,103781.00,76798.0,130764.00,NaN,103781.0,103781.0,"['jira', 'sql']",Senior
643,Senior Performance Marketing (Data Analyst),EDWARD JONES,"Dixon, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['15 hours ago', '90,628–154,313 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgUGVyZm9ybWFuY2UgTW...,NaN,15 hours ago,Full-time,...,90628–154313,a year,122470.50,90628.0,154313.00,NaN,122470.5,122470.5,"['tableau', 'excel', 'sas', 'hadoop', 'power_b...",Senior
644,Senior Data Analyst (ServiceNow),Applied Memetics L.L.C,United States,via My ArkLaMiss Jobs,"Overview:AM LLC is seeking a Data Analyst, Sen...","['17 hours ago', '100,815–110,815 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0IC...,NaN,17 hours ago,Full-time,...,100815–110815,a year,105815.00,100815.0,110815.00,NaN,105815.0,105815.0,['go'],Senior
645,Senior Performance Marketing (Data Analyst),EDWARD JONES,"Jerome, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['20 hours ago', '90,628–154,313 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgUGVyZm9ybWFuY2UgTW...,NaN,20 hours ago,Full-time,...,90628–154313,a year,122470.50,90628.0,154313.00,NaN,122470.5,122470.5,"['tableau', 'excel', 'sas', 'hadoop', 'power_b...",Senior

6. Intern or Junior Jobs

In [25]:
pd.read_sql(
    """
    SELECT *
FROM jobs
WHERE experience_level = 'Intern'
OR experience_level = 'Junior';
""",
    conn
)

,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,...,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens,experience_level
0,International Data,Morgan Stanley,United States,via BeBee,Job Description - International Data & Busines...,"['21 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJJbnRlcm5hdGlvbmFsIERhdGEiLC...,NaN,21 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'powerpoint', 'excel', 'sql', 'pyt...",Intern
1,Jr. Data Analyst,Aquent Talent,Anywhere,via LinkedIn,Job Title: Jr Data Analyst\n\nClient Location:...,"['9 hours ago', 'Work from home', 'Contractor']",eyJqb2JfdGl0bGUiOiJKci4gRGF0YSBBbmFseXN0IiwiaH...,https://encrypted-tbn0.gstatic.com/images?q=tb...,9 hours ago,Contractor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql'],Junior
2,Jr. Data Analyst,Aquent Talent,Anywhere,via LinkedIn,Job Title: Jr Data Analyst\n\nClient Location:...,"['9 hours ago', 'Work from home', 'Contractor']",eyJqb2JfdGl0bGUiOiJKci4gRGF0YSBBbmFseXN0IiwiaH...,https://encrypted-tbn0.gstatic.com/images?q=tb...,9 hours ago,Contractor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql'],Junior
3,"2023 Intern Conversion: 2024 FT Data Analyst III,",Walmart,"Bentonville, AR",via BeBee,What you'll do at\n\nPosition Summary...\n\nWh...,"['22 hours ago', 'Internship', 'Health insuran...",eyJqb2JfdGl0bGUiOiIyMDIzIEludGVybiBDb252ZXJzaW...,https://encrypted-tbn0.gstatic.com/images?q=tb...,22 hours ago,Internship,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'power_bi', 'excel', 'sas', 'power...",Intern
4,Junior Data Analyst/Scientist Role - Contract ...,Upwork,Anywhere,via Upwork,"Company\n\nThe TAC Index provides independent,...","['17 hours ago', 'Work from home', 'Contractor...",eyJqb2JfdGl0bGUiOiJKdW5pb3IgRGF0YSBBbmFseXN0L1...,NaN,17 hours ago,Contractor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['mysql', 'matlab', 'pandas', 'matplotlib', 'r...",Junior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,Problem Management Business Data Analyst Intern,Corporate,"Columbia, MO",via My ArkLaMiss Jobs,You could be the one who changes everything fo...,"['8 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJQcm9ibGVtIE1hbmFnZW1lbnQgQn...,NaN,8 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],Intern
2112,Data Analyst Intern - Undergraduate,Corporate,"Columbia, MO",via My ArkLaMiss Jobs,You could be the one who changes everything fo...,['18 hours ago'],eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSW50ZXJuIC...,NaN,18 hours ago,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql'],Intern
2113,Data Analyst Intern,First Orion,"Benton, AR",via My ArkLaMiss Jobs,First Orion is actively seeking a Data Analyst...,"['20 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSW50ZXJuIi...,NaN,20 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['redshift', 'aws', 'sql', 'nosql']",Intern
2114,Data Analyst Intern (Undergraduate),Corporate,"Columbia, MO",via My ArkLaMiss Jobs,You could be the one who changes everything fo...,"['21 hours ago', 'Internship']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSW50ZXJuIC...,NaN,21 hours ago,Internship,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql'],Intern
2115,Data Analyst Intern (Undergraduate),Corporate,"Jefferson City, MO",via My ArkLaMiss Jobs,You could be the one who changes everything fo...,"['21 hours ago', 'Internship']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSW50ZXJuIC...,NaN,21 hours ago,Internship,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql'],Intern

7. Top 5 Companies Offering Senior Jobs with Salary > $100,000

In [26]:
pd.read_sql(
    """
    SELECT
    company_name,
    COUNT(*) AS total_jobs
FROM jobs
WHERE experience_level = 'Senior'
AND salary_standardized > 100000
GROUP BY company_name
ORDER BY total_jobs DESC
LIMIT 5;
""",
    conn
)

   company_name  total_jobs
0  Talentify.io          29
1       Harnham          29
2       Walmart          19
3        Upwork          18
4  EDWARD JONES          18

8: Top Hiring Locations

In [27]:
pd.read_sql(
    """
    SELECT 
    location,
    COUNT(*) AS total_jobs
    FROM jobs 
    GROUP BY location
    ORDER BY total_jobs DESC
    LIMIT 20;
    """,
    conn
)

                   location  total_jobs
0                 Anywhere        18067
1          United States          10011
2                  Anywhere        9915
3             United States        5547
4                Denver, CO        1062
5      Oklahoma City, OK           1028
6        Kansas City, MO            840
7           Kansas City, MO         573
8     Jefferson City, MO            550
9      Colorado Springs, CO         512
10       Bentonville, AR            422
11        Oklahoma City, OK         409
12       Jefferson City, MO         371
13               Aurora, CO         346
14            Topeka, KS            310
15           Wichita, KS            307
16             Tulsa, OK            297
17     Overland Park, KS            270
18            Englewood, CO         254
19             Columbia, MO         218

9: Experience Level Distribution

In [28]:
pd.read_sql(
    """
    SELECT 
    experience_level,
    COUNT(*) AS total_jobs
    FROM jobs
    GROUP BY experience_level
    ORDER BY total_jobs DESC
    """,
    conn
)

  experience_level  total_jobs
0              Mid       45532
1           Senior       10308
2             Lead        2557
3          Manager        1440
4           Intern        1234
5           Junior         882

10: Salary Statistics

In [30]:
pd.read_sql(
    """
    SELECT 
    MIN(salary_standardized) AS minimum_salary,
    MAX(salary_standardized) AS maximum_salary,
    AVG(salary_standardized) AS average_salary
    FROM jobs;
    """,
    conn

)

   minimum_salary  maximum_salary  average_salary
0         15080.0        624000.0    92289.425683

11: Remote Jobs Only

In [34]:
pd.read_sql(
    """
    SELECT *
    FROM jobs
    WHERE work_from_home = 1;
    """,
    conn

)

,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,...,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens,experience_level
0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,15 hours ago,Full-time,...,101K–143K,a year,122000.00,101000.0,143000.00,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']",Mid
1,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,NaN,12 hours ago,Contractor,...,15–25,an hour,20.00,15.0,25.00,20.00,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']",Mid
2,Data Analyst (Model Validation),Swedbank,Anywhere,via JobTeaser,"Are you passionate about Credit Risk, Data Ana...","['17 hours ago', 'Work from home', 'Full-time'...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgKE1vZGVsIF...,https://encrypted-tbn0.gstatic.com/images?q=tb...,17 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['python', 'sas', 'sql', 'spss']",Mid
3,IT Financial Data Analyst Lead,Progressive,Anywhere,via Jobgether,"This a Full Remote job, the offer is available...","['7 hours ago', 'Work from home', 'Full-time',...",eyJqb2JfdGl0bGUiOiJJVCBGaW5hbmNpYWwgRGF0YSBBbm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,7 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],Lead
4,Senior Data Analyst,Aquent,Anywhere,via LinkedIn,The Research Data Analyst is responsible for d...,"['14 hours ago', '54.00–60.52 an hour', 'Work ...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,https://encrypted-tbn0.gstatic.com/images?q=tb...,14 hours ago,NaN,...,54.00–60.52,an hour,57.26,54.0,60.52,57.26,NaN,119100.8,['sql'],Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27975,Earthquake Analyst,University of Kansas,Anywhere,via ZipRecruiter,Up to 50% of work may be performed remotely on...,"['23 hours ago', 'Work from home', 'Full-time']",eyJqb2JfdGl0bGUiOiJFYXJ0aHF1YWtlIEFuYWx5c3QiLC...,NaN,23 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql'],Mid
27976,Analyst I - REMOTE,Broadbean,Anywhere,via ZipRecruiter,Job Details SUMMARY HSAG is nationally recogni...,"['23 hours ago', 'Work from home', 'Full-time'...",eyJqb2JfdGl0bGUiOiJBbmFseXN0IEkgLSBSRU1PVEUiLC...,https://encrypted-tbn0.gstatic.com/images?q=tb...,23 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'excel', 'sas', 'word']",Mid
27977,Analyst I - REMOTE,Broadbean,Anywhere,via ZipRecruiter,Job Details SUMMARY HSAG is nationally recogni...,"['23 hours ago', 'Work from home', 'Full-time'...",eyJqb2JfdGl0bGUiOiJBbmFseXN0IEkgLSBSRU1PVEUiLC...,https://encrypted-tbn0.gstatic.com/images?q=tb...,23 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'excel', 'sas', 'word']",Mid
27978,HEDIS Data/Quality Analyst,TEKsystems,Anywhere,via ZipRecruiter,Description:\n\nLocation – Open to Remote (Min...,"['23 hours ago', 'Work from home', 'Full-time'...",eyJqb2JfdGl0bGUiOiJIRURJUyBEYXRhL1F1YWxpdHkgQW...,https://encrypted-tbn0.gstatic.com/images?q=tb...,23 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['power_bi', 'tableau', 'sql']",Mid
27979,Analytics Engineer (IT),Precision Castparts Corp.,Anywhere,via ZipRecruiter,The Analytics Engineer will use cloud-based to...,"['24 hours ago', 'Work from home', 'Full-time']",eyJqb2JfdGl0bGUiOiJBbmFseXRpY3MgRW5naW5lZXIgKE...,https://encrypted-tbn0.gstatic.com/images?q=tb...,24 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['power_bi', 'sql', 'dax']",Mid

Companies Starting with "A" (LIKE)

In [37]:
pd.read_sql(
    """
    SELECT *
    FROM jobs
    WHERE company_name LIKE "A%"
    """,
    conn

)

,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,...,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens,experience_level
0,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,12 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],Mid
1,Data Analyst,AEG,United States,via IT Job Depot,"In order to be considered for this role, after...","['8 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,8 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['power_bi', 'tableau', 'jira', 'snowflake', '...",Mid
2,Senior Data Analyst,Aquent,Anywhere,via LinkedIn,The Research Data Analyst is responsible for d...,"['14 hours ago', '54.00–60.52 an hour', 'Work ...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,https://encrypted-tbn0.gstatic.com/images?q=tb...,14 hours ago,NaN,...,54.00–60.52,an hour,57.26,54.0,60.52,57.26,NaN,119100.8,['sql'],Senior
3,Senior Data Analyst,Amplify,United States,via Jobs Trabajo.org,"A pioneer in K-12 education since 2000, Amplif...","['12 hours ago', 'Full-time', 'No degree menti...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,https://encrypted-tbn0.gstatic.com/images?q=tb...,12 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'aws', 'looker', 'snowflake', 'air...",Senior
4,Data Analyst,"Aara Technologies, Inc","Fort Smith, AR",via Jobs Trabajo.org,Qualifications:\n• Bachelor's degree in Mathem...,"['13 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,13 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['excel', 'power_bi', 'tableau', 'r', 'python'...",Mid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4323,Senior Data Analyst (ServiceNow),Applied Memetics L.L.C,United States,via My ArkLaMiss Jobs,"Overview:AM LLC is seeking a Data Analyst, Sen...","['17 hours ago', '100,815–110,815 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0IC...,NaN,17 hours ago,Full-time,...,100815–110815,a year,105815.00,100815.0,110815.00,NaN,105815.0,105815.0,['go'],Senior
4324,Data Analyst,"Aara Technologies, Inc","Kansas City, MO",via My ArkLaMiss Jobs,Job Description:\n\nWe are seeking a Data Anal...,"['19 hours ago', 'Full-time', 'No degree menti...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,NaN,19 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],Mid
4325,HR Data Analyst,"America's CAR-MART, Inc.","Rogers, AR",via My ArkLaMiss Jobs,"Summary\n\nSuccessfully evaluates, analyzes an...","['20 hours ago', 'Full-time', 'No degree menti...",eyJqb2JfdGl0bGUiOiJIUiBEYXRhIEFuYWx5c3QiLCJodG...,NaN,20 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],Mid
4326,Salesforce Data Analyst,Aquent Talent,United States,via My ArkLaMiss Jobs,Salary: $30.00 Hr\nOverview\n...\nJob descript...,"['20 hours ago', '30 an hour', 'Full-time', 'N...",eyJqb2JfdGl0bGUiOiJTYWxlc2ZvcmNlIERhdGEgQW5hbH...,NaN,20 hours ago,Full-time,...,30,an hour,30.00,NaN,NaN,30.00,NaN,62400.0,"['excel', 'sql']",Mid
4327,Data Analyst,Advantage Tech,"Overland Park, KS",via My ArkLaMiss Jobs,What you will do:\n• Build reporting dashboard...,"['23 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,NaN,23 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'sql']",Mid

13: Salary Between 80K and 120K (BETWEEN)

In [39]:
pd.read_sql(
    """
    SELECT *
    FROM jobs
    WHERE salary_standardized BETWEEN 80000 AND 120000;
    """,
    conn
)

,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,...,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens,experience_level
0,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,7 hours ago,Contractor,...,90K–110K,a year,100000.00,90000.0,110000.00,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']",Mid
1,Senior Data Analyst,Aquent,Anywhere,via LinkedIn,The Research Data Analyst is responsible for d...,"['14 hours ago', '54.00–60.52 an hour', 'Work ...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,https://encrypted-tbn0.gstatic.com/images?q=tb...,14 hours ago,NaN,...,54.00–60.52,an hour,57.26,54.0,60.52,57.26,NaN,119100.8,['sql'],Senior
2,Mid-level Claims Data Analyst,CIBA Insurance Services,United States,via KSNT Jobs,"Established in 1993, CIBA Insurance Services o...","['10 hours ago', '90K–130K a year', 'Full-time...",eyJqb2JfdGl0bGUiOiJNaWQtbGV2ZWwgQ2xhaW1zIERhdG...,NaN,10 hours ago,Full-time,...,90K–130K,a year,110000.00,90000.0,130000.00,NaN,110000.0,110000.0,"['excel', 'mssql', 'ssrs', 'sql']",Mid
3,Analyst/Developer - General 2 17002-1,ISG,United States,via LinkedIn,Job Title & ID #: Analyst/Developer - General ...,"['7 hours ago', '49.25 an hour', 'Contractor']",eyJqb2JfdGl0bGUiOiJBbmFseXN0L0RldmVsb3BlciAtIE...,https://encrypted-tbn0.gstatic.com/images?q=tb...,7 hours ago,Contractor,...,49.25,an hour,49.25,NaN,NaN,49.25,NaN,102440.0,"['power_bi', 'sas', 'sharepoint', 'snowflake',...",Mid
4,Business Data Analyst,Eliassen Group,Anywhere,via LinkedIn,Are you a skilled Business Data Analyst with a...,"['12 hours ago', '88K–105K a year', 'Work from...",eyJqb2JfdGl0bGUiOiJCdXNpbmVzcyBEYXRhIEFuYWx5c3...,https://encrypted-tbn0.gstatic.com/images?q=tb...,12 hours ago,Full-time,...,88K–105K,a year,96500.00,88000.0,105000.00,NaN,96500.0,96500.0,"['sap', 'sql']",Mid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3719,Marketing Data & BI Analyst II,EDWARD JONES,"Sweet Springs, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['21 hours ago', '76,798–130,764 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJNYXJrZXRpbmcgRGF0YSBcdTAwMj...,NaN,21 hours ago,Full-time,...,76798–130764,a year,103781.00,76798.0,130764.00,NaN,103781.0,103781.0,"['power_bi', 'tableau', 'excel', 'snowflake', ...",Mid
3720,Data Analyst II,EDWARD JONES,"St James, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['21 hours ago', '76,798–130,764 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSUkiLCJodG...,NaN,21 hours ago,Full-time,...,76798–130764,a year,103781.00,76798.0,130764.00,NaN,103781.0,103781.0,"['power_bi', 'excel', 'sas', 'snowflake', 'sql...",Mid
3721,Data Analyst II,EDWARD JONES,"Rolla, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['22 hours ago', '76,798–130,764 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSUkiLCJodG...,NaN,22 hours ago,Full-time,...,76798–130764,a year,103781.00,76798.0,130764.00,NaN,103781.0,103781.0,"['power_bi', 'excel', 'sas', 'snowflake', 'sql...",Mid
3722,Data Analyst II,EDWARD JONES,"St James, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['22 hours ago', '76,798–130,764 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSUkiLCJodG...,NaN,22 hours ago,Full-time,...,76798–130764,a year,103781.00,76798.0,130764.00,NaN,103781.0,103781.0,"['power_bi', 'excel', 'sas', 'snowflake', 'sql...",Mid
3723,Marketing Data & BI Analyst II,EDWARD JONES,"Houstonia, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '76,798–130,764 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJNYXJrZXRpbmcgRGF0YSBcdTAwMj...,NaN,23 hours ago,Full-time,...,76798–130764,a year,103781.00,76798.0,130764.00,NaN,103781.0,103781.0,"['power_bi', 'tableau', 'excel', 'snowflake', ...",Mid

14: Experience Level Using IN

In [ ]:
pd.read_sql(
    """
    SELECT * 
    FROM jobs
    WHERE experience_level IN ("Intern","Junior","Mid");
    """,
    conn
)

,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,...,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens,experience_level
0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,15 hours ago,Full-time,...,101K–143K,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']",Mid
1,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,12 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],Mid
2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",via Indeed,Overview:\n\nWe are seeking a full-time...\nAe...,"['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...,NaN,18 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql'],Mid
3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,NaN,12 hours ago,Contractor,...,15–25,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']",Mid
4,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,7 hours ago,Contractor,...,90K–110K,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']",Mid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47643,Data Analyst,Advantage Tech,"Overland Park, KS",via My ArkLaMiss Jobs,What you will do:\n• Build reporting dashboard...,"['23 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,NaN,23 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'sql']",Mid
47644,Data Analyst,Tulsa Remote,"Vera, OK",via My ArkLaMiss Jobs,• InTulsa is partnering with Tulsa Remote to f...,"['23 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,NaN,23 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['bigquery', 'excel', 'javascript', 'power_bi'...",Mid
47645,Data Analyst - Remote,UnitedHealth Group,United States,via My ArkLaMiss Jobs,Combine two of the fastest-growing fields on t...,"['23 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBSZW1vdG...,NaN,23 hours ago,Full-time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['pyspark', 'go', 'sql', 'word', 'r', 'python']",Mid
47646,Marketing Data & BI Analyst II,EDWARD JONES,"Houstonia, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '76,798–130,764 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJNYXJrZXRpbmcgRGF0YSBcdTAwMj...,NaN,23 hours ago,Full-time,...,76798–130764,a year,103781.0,76798.0,130764.0,NaN,103781.0,103781.0,"['power_bi', 'tableau', 'excel', 'snowflake', ...",Mid
47647,Institutional Credit Management - Lending Data...,Citi,United States,via My ArkLaMiss Jobs,The Institutional Credit Management (ICM) grou...,"['24 hours ago', '105,850–158,780 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJJbnN0aXR1dGlvbmFsIENyZWRpdC...,https://encrypted-tbn0.gstatic.com/images?q=tb...,24 hours ago,Full-time,...,105850–158780,a year,132315.0,105850.0,158780.0,NaN,132315.0,132315.0,"['tableau', 'cognos']",Mid

15: Companies with More Than 100 Job Postings (HAVING)

In [43]:
pd.read_sql(
    """
    SELECT  
    company_name,
    COUNT(*) AS total_jobs
    FROM jobs
    GROUP BY company_name
    HAVING COUNT(*)>100
    ORDER  BY total_jobs DESC;
    """,
    conn
)

                               company_name  total_jobs
0                                    Upwork        7533
1                              Talentify.io        2118
2                                   Walmart        1829
3                              vmysmartpros        1415
4                                      Dice         862
5                              EDWARD JONES         747
6                                 Corporate         612
7                        Cox Communications         538
8                            Insight Global         483
9                                      iSay         353
10                              MYSMARTPROS         266
11                      Centene Corporation         242
12                                      ATC         199
13                                  Harnham         171
14         Staffigo Technical Services, LLC         167
15                             Apex Systems         163
16                                   Leidos         151
17         Saint Louis County Clerks Office         138
18                               Sam's Club         136
19                            CareerBuilder         136
20                            SynergisticIT         133
21                            Jobs via Dice         132
22  General Dynamics Information Technology         132
23                        State of Missouri         130
24                                   R1 RCM         127
25                          Cardinal Health         126
26                              Robert Half         124
27                                    Jobot         123
28                       UnitedHealth Group         119
29                          Elevance Health         113
30                                 FlexJobs         110
31                                     CACI         107
32                                   Oracle         102